version: "3.8"
services:
  mongodb:
    image: mongo:7.0
    container_name: fleetlink-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ""
      MONGO_INITDB_ROOT_PASSWORD: ""
      MONGO_INITDB_DATABASE: fleetlink
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - fleetlink-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fleetlink-backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 4000
      MONGODB_URI: ""
      JWT_SECRET: elkgnedkjgnergkerngekorgneriognerokldfnmbkldfsnbsdkoffgberopgjeroij
      RATE_LIMIT_WINDOW_MS: 900000
      RATE_LIMIT_MAX_REQUESTS: 100
    ports:
      - "4000:4000"
    depends_on:
      - mongodb
    networks:
      - fleetlink-network
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: fleetlink-frontend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: http://localhost:4000/api
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - fleetlink-network
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  mongodb_data:

networks:
  fleetlink-network:
    driver: bridge
